[2021-03-01 20:37:42,745] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-23T00:00:00+00:00 [queued]>
[2021-03-01 20:37:42,750] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-23T00:00:00+00:00 [queued]>
[2021-03-01 20:37:42,750] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-03-01 20:37:42,750] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-03-01 20:37:42,750] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-03-01 20:37:42,759] {taskinstance.py:1038} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-01-23T00:00:00+00:00
[2021-03-01 20:37:42,761] {standard_task_runner.py:51} INFO - Started process 237826 to run task
[2021-03-01 20:37:42,764] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-01-23T00:00:00+00:00', '--job-id', '154', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp3l1fjiic']
[2021-03-01 20:37:42,764] {standard_task_runner.py:76} INFO - Job 154: Subtask is_api_available
[2021-03-01 20:37:42,787] {logging_mixin.py:103} INFO - Running <TaskInstance: user_processing.is_api_available 2020-01-23T00:00:00+00:00 [running]> on host pop-os.localdomain
[2021-03-01 20:37:42,805] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-01-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-23T00:00:00+00:00
[2021-03-01 20:37:42,805] {http.py:102} INFO - Poking: api/
[2021-03-01 20:37:42,807] {base.py:74} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: None
[2021-03-01 20:37:42,809] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-03-01 20:37:42,971] {base.py:245} INFO - Success criteria met. Exiting.
[2021-03-01 20:37:42,975] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200123T000000, start_date=20210302T013742, end_date=20210302T013742
[2021-03-01 20:37:43,007] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-01 20:37:43,015] {local_task_job.py:118} INFO - Task exited with return code 0
