[2021-03-01 20:59:16,240] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-08-19T00:00:00+00:00 [queued]>
[2021-03-01 20:59:16,245] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-08-19T00:00:00+00:00 [queued]>
[2021-03-01 20:59:16,245] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-03-01 20:59:16,245] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-03-01 20:59:16,245] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-03-01 20:59:16,255] {taskinstance.py:1038} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-08-19T00:00:00+00:00
[2021-03-01 20:59:16,257] {standard_task_runner.py:51} INFO - Started process 263820 to run task
[2021-03-01 20:59:16,260] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-08-19T00:00:00+00:00', '--job-id', '1199', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmproc_vsye']
[2021-03-01 20:59:16,260] {standard_task_runner.py:76} INFO - Job 1199: Subtask is_api_available
[2021-03-01 20:59:16,312] {logging_mixin.py:103} INFO - Running <TaskInstance: user_processing.is_api_available 2020-08-19T00:00:00+00:00 [running]> on host pop-os.localdomain
[2021-03-01 20:59:16,342] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-08-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-08-19T00:00:00+00:00
[2021-03-01 20:59:16,343] {http.py:102} INFO - Poking: api/
[2021-03-01 20:59:16,346] {base.py:74} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: None
[2021-03-01 20:59:16,348] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-03-01 20:59:16,536] {base.py:245} INFO - Success criteria met. Exiting.
[2021-03-01 20:59:16,545] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200819T000000, start_date=20210302T015916, end_date=20210302T015916
[2021-03-01 20:59:16,576] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-01 20:59:16,591] {local_task_job.py:118} INFO - Task exited with return code 0
