[2021-03-01 20:36:08,753] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-08T00:00:00+00:00 [queued]>
[2021-03-01 20:36:08,759] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-08T00:00:00+00:00 [queued]>
[2021-03-01 20:36:08,759] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-03-01 20:36:08,759] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-03-01 20:36:08,760] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-03-01 20:36:08,769] {taskinstance.py:1038} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-01-08T00:00:00+00:00
[2021-03-01 20:36:08,772] {standard_task_runner.py:51} INFO - Started process 235918 to run task
[2021-03-01 20:36:08,775] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-01-08T00:00:00+00:00', '--job-id', '79', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpoedob1zl']
[2021-03-01 20:36:08,775] {standard_task_runner.py:76} INFO - Job 79: Subtask is_api_available
[2021-03-01 20:36:08,800] {logging_mixin.py:103} INFO - Running <TaskInstance: user_processing.is_api_available 2020-01-08T00:00:00+00:00 [running]> on host pop-os.localdomain
[2021-03-01 20:36:08,819] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-01-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-08T00:00:00+00:00
[2021-03-01 20:36:08,820] {http.py:102} INFO - Poking: api/
[2021-03-01 20:36:08,823] {base.py:74} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: None
[2021-03-01 20:36:08,824] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-03-01 20:36:08,940] {base.py:245} INFO - Success criteria met. Exiting.
[2021-03-01 20:36:08,949] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200108T000000, start_date=20210302T013608, end_date=20210302T013608
[2021-03-01 20:36:08,988] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-01 20:36:09,026] {local_task_job.py:118} INFO - Task exited with return code 0
