[2021-03-01 21:00:44,152] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-09-03T00:00:00+00:00 [queued]>
[2021-03-01 21:00:44,156] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-09-03T00:00:00+00:00 [queued]>
[2021-03-01 21:00:44,156] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-03-01 21:00:44,156] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-03-01 21:00:44,156] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-03-01 21:00:44,164] {taskinstance.py:1038} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-09-03T00:00:00+00:00
[2021-03-01 21:00:44,166] {standard_task_runner.py:51} INFO - Started process 265533 to run task
[2021-03-01 21:00:44,169] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-09-03T00:00:00+00:00', '--job-id', '1274', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp826u4_z_']
[2021-03-01 21:00:44,169] {standard_task_runner.py:76} INFO - Job 1274: Subtask is_api_available
[2021-03-01 21:00:44,190] {logging_mixin.py:103} INFO - Running <TaskInstance: user_processing.is_api_available 2020-09-03T00:00:00+00:00 [running]> on host pop-os.localdomain
[2021-03-01 21:00:44,215] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-09-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-09-03T00:00:00+00:00
[2021-03-01 21:00:44,216] {http.py:102} INFO - Poking: api/
[2021-03-01 21:00:44,218] {base.py:74} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: None
[2021-03-01 21:00:44,219] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-03-01 21:00:44,314] {base.py:245} INFO - Success criteria met. Exiting.
[2021-03-01 21:00:44,317] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200903T000000, start_date=20210302T020044, end_date=20210302T020044
[2021-03-01 21:00:44,341] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-01 21:00:44,380] {local_task_job.py:118} INFO - Task exited with return code 0
